import { Inter } from "next/font/google";
import "./globals.css";

const getInter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: "400"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${getInter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
